version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Build phase complete
artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/**
