kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616

  type: NodePort


---

kind: Service
apiVersion: v1
metadata:
  name: fleetmant-position-tracker
spec:
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP

---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  type: ClusterIP

---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

